# Generated by Django 4.0.3 on 2023-05-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
