# Generated by Django 4.0.3 on 2023-05-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
    ]
