# Generated by Django 4.0.3 on 2023-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label1', models.CharField(max_length=200)),
                ('label2', models.CharField(max_length=200)),
                ('label3', models.CharField(max_length=200)),
                ('label4', models.CharField(max_length=200)),
                ('label5', models.CharField(max_length=200)),
                ('label6', models.CharField(max_length=200)),
                ('label7', models.CharField(max_length=200)),
                ('label8', models.CharField(max_length=200)),
                ('label9', models.CharField(max_length=200)),
                ('label10', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LabelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200)),
            ],
        ),
    ]
