# Generated by Django 4.0.3 on 2023-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_labellists_label1_alter_labellists_label10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelname',
            name='label_name',
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName10',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='labelName9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
