# Generated by Django 4.0.3 on 2023-05-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_labelname_label_name_labelname_labelname1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labellists',
            name='label10',
        ),
        migrations.RemoveField(
            model_name='labelname',
            name='labelName10',
        ),
    ]
