# Generated by Django 4.0.3 on 2023-05-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_labellists_label10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='labellists',
            name='imgName',
            field=models.CharField(default='img', max_length=200),
            preserve_default=False,
        ),
    ]
